---
title: "Status Quo of Content Creators on a video sharing platform"
author: "Hongtao Jiang, Yujia Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction

The number of content creators on a streaming platform for Gen Z in China reached a peak in recent years with a total of over 20 million+ active creators and an increase of 600k+ each month. However, while the growing speed of the quantity is optimistic, we want to take a deeper look at the quantity of the content creators. Furthermore, like other video-sharing platforms such as YouTube, creators with different size fan bases could be diverse; and the status for creators with varying topics of video could also be different.

Therefore, in this project, we want to understand the status quo of the platform's content creators with various features and analyze the differences. We are going to present our analysis in four parts:

1.  Analysis of the Overall Status

2.  Analysis of content creators' growth path

3.  Analysis of content creators' retention

4.  Analysis of content creators' tags and how different tags differ
